#Para conexion del cliente
THIS_CLIENT_ID = "BACCHUS'S TORRCLIENT"
#THIS_CLIENT_ID= "FSTSEEDER TORRCLIENT"
PORT = 9200
MAX_UPLOAD_PEERS = 4

#Constantes de bloques y piezas
DEF_BLOCK_LENGTH = 16384
DEF_PIECE_LENGTH = 524288



